get-gen:
    rsync -avz --progress scuni:"Istvans-TSGBench/models/'$(basename "$PWD")'/gen" .

init:
    rm -rf Time_Transformer
    git clone https://github.com/Lysarthas/Time-Transformer.git Time_Transformer
    (cd Time_Transformer && git checkout ff8faa27353e721702aaa51136192f071e5a5e19)


