name: tsgbench
dependencies:
- python=3.7.16
- pandas=1.3.5
- scipy=1.7.3
- numpy=1.21.5
- statsmodels=0.13.5
- matplotlib=3.5.3
- scikit-learn=1.0.2
- seaborn=0.12.2
- conda-forge::pyprojroot=0.3.0
- pip
- pip:
  - torch==1.13.1
  - mgzip==0.2.1
  - dtaidistance==2.3.12
  - tensorflow==1.15
