test_run:
    python run_tts_gan.py --dataset_no 2 --exp_name D2


pull-tts-gan:
    rm -rf TTS_GAN
    git clone git@github.com:istvan-derda/istvans-tts-gan.git TTS_GAN
    $(cd TTS_GAN && git checkout 50d8aeefec21438090ef73117ee4d7017ddaf656)
