test_run:
    python run_tts_gan.py --dataset_no 2 --exp_name D2


pull-tts-gan:
    rm -rf TTS_GAN
    git clone git@github.com:istvan-derda/istvans-tts-gan.git TTS_GAN
    $(cd TTS_GAN && git checkout 401c579540e54c09b56f80f8677a97c9d23d36a1)
