test_run:
    python run_tts_gan.py --dataset_no 2 --exp_name D2


pull-tts-gan:
    rm -rf TTS_GAN
    git clone git@github.com:istvan-derda/istvans-tts-gan.git TTS_GAN
    $(cd TTS_GAN && git checkout 84d777e1e9e185d30124eecbf45f953ce88d31c8)
