init:
    rm -rf Time_GAN
    git clone git@github.com:jsyoon0823/TimeGAN.git Time_GAN
    $(cd Time_GAN && git checkout 8f6181cb9b9d2fa0c930cd902411d9ac8a308e07)

get-gen:
    rsync -avz --progress wi34sasa@login01.sc.uni-leipzig.de:"Istvans-TSGBench/models/$(basename "$PWD")/gen" .
