init:
    rm -rf Time_VQVAE
    git clone https://github.com/ML4ITS/TimeVQVAE.git Time_VQVAE
    $(cd Time_VQVAE && git checkout 6e04f698a8f0d6935c2e39e044b6d2eebca121de)

get-gen:
    rsync -avz --progress scuni:"Istvans-TSGBench/models/$(basename "$PWD")/gen" .
