init:
    rm -rf Time_VQVAE
    git clone git@github.com:istvan-derda/TimeVQVAE_tsgb-patch.git Time_VQVAE
    $(cd Time_VQVAE && git checkout 275abba9863209a8ee30971ae883da4ebd619f92)

get-gen:
    rsync -avz --progress wi34sasa@login01.sc.uni-leipzig.de:"Istvans-TSGBench/models/$(basename "$PWD")/gen" .
