run_transfusion *args: docker-build
    docker run --rm \
    -v $(pwd)/../../:/TSGBench \
    -w /TSGBench/models/TransFusion \
    transfusion \
    python run_transfusion.py {{args}}

docker-build:
    docker build -t transfusion docker-image

init:
    rm -rf TransFusion
    git clone git@github.com:istvan-derda/Istvans-TransFusion.git TransFusion
    $(cd TransFusion && git checkout f13a83ff5532aca8e86ec6186b9f24bd1ab70630)

get-gen:
    rsync -avz --progress scuni:"Istvans-TSGBench/models/$(basename "$PWD")/gen" .
