run_transfusion *args: docker-build
    docker run --rm \
    -v $(pwd)/../../:/TSGBench \
    -w /TSGBench/models/TransFusion \
    transfusion \
    python run_transfusion.py {{args}}

docker-build:
    docker build -t transfusion docker-image

init:
    rm -rf TransFusion
    git clone git@github.com:istvan-derda/Istvans-TransFusion.git TransFusion
    $(cd TransFusion && git checkout 61c55d31bf8f64ec3d60e57c156a3a9b2b25ab7f)

get-gen:
    rsync -avz --progress scuni:"Istvans-TSGBench/models/$(basename "$PWD")/gen" .
