run_transfusion *args: docker-build
    docker run --rm \
    -v $(pwd)/../../:/TSGBench \
    -w /TSGBench/models/TransFusion \
    transfusion \
    python run_transfusion.py {{args}}

docker-build:
    docker build -t transfusion docker-image

pull-transfusion:
    rm -rf TransFusion
    git clone git@github.com:istvan-derda/Istvans-TransFusion.git TransFusion
    $(cd TransFusion && git checkout e0f0a62d5a39c45b6d8a1a37b7d163b79194d390)
